### ISSUE TITLE
Recording not playable in Chrome.

### ISSUE THREAD

**Issue by darkpssngr** [Five9DeveloperProgram/Five9CTISample#5]
I'm uploading my recordings to my ftp server and I've added a call variable called recording url which returns the recording url of the uploaded file. However chrome is unable to decode the generated wav file. Its only playable in safari.

Is it possible to change some setting so that the wav file generated is playable in chrome?

Thanks

**Comment by joshso** [comment]
Five9 provides recordings in WAV/gsm by default and WAV/ulaw as an option, neither of which are supported by [Chrome's audio player](https://sites.google.com/a/chromium.org/dev/audio-video).

Possible solutions:

- Configure Chrome to open the file with a media player app instead that supports those formats (VLC, WMP...)
- Convert to an alternate format once the file has been uploaded to your ftp
